---
- hosts: all
  tasks:
    - include: tasks/systemd.yml
      tags: default
    - include: tasks/general.yml
      tags: default
    - include: tasks/mysql.yml
      tags: default
    - include: tasks/php5-fpm.yml    
      tags: default
    - include: tasks/nginx.yml
      tags: default
    - include: tasks/phpmyadmin.yml
      tags: phpMyAdmin
    - include: tasks/DevAAC.yml
      tags: DevAAC
    - include: tasks/tfs.yml
      tags: tfs
    - include: tasks/tfs-old.yml
      tags: tfs-old
    - include: tasks/general-last.yml
    - include: tasks/wine.yml
      tags: wine

  handlers:
    - name: restart systemd-journald
      service: name=systemd-journald state=restarted
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart php5-fpm
      service: name=php5-fpm state=restarted

    - name: restart mysql
      service: name=mysql state=restarted
 