---
- name: Install MySQL Server and backup packages
  apt: pkg={{ item }} state=latest
  with_items:
   - mariadb-server
   - python-mysqldb
   - automysqlbackup

- name: Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Generate random MySQL root password
  command: openssl rand -base64 18
  register: randompass

- name: Set MySQL otsmanager password (localhost)
  mysql_user: name=otsmanager password={{randompass.stdout}} host=localhost priv=*.*:ALL,GRANT check_implicit_admin=yes

- name: Save MySQL otsmanager password
  template: src=.my.cnf dest=/home/otsmanager/.my.cnf owner=otsmanager group=otsmanager mode=0600
  
- name: Set MySQL otsmanager password (%)
  mysql_user: name=otsmanager password={{randompass.stdout}} host=% priv=*.*:ALL,GRANT check_implicit_admin=yes

- name: Allow otsmanager to access automysqlbackup directory
  file: path=/var/lib/automysqlbackup state=directory group=otsmanager
