---
- name: Install Mysql Server package
  apt: pkg={{ item }} state=latest
  with_items:
   - mysql-server
   - python-mysqldb

- name: Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Generate random MySQL root password
  command: openssl rand -base64 20
  register: randompass

- name: Set MySQL root password (localhost)
  mysql_user: name=root password={{randompass.stdout}} host=localhost priv=*.*:ALL,GRANT check_implicit_admin=yes
  
- name: Set MySQL root password (%)
  mysql_user: name=root password={{randompass.stdout}} host=% priv=*.*:ALL,GRANT check_implicit_admin=yes

- name: Save MySQL root password
  template: src=.my.cnf dest=/root/.my.cnf owner=root group=root mode=0600

- name: Delete MySQL root accounts we don't want
  mysql_user: name=root host={{item}} state=absent check_implicit_admin=yes
  with_items:
    - "{{ hostname }}"
    - 127.0.0.1
    - ::1

- name: Ensure anonymous MySQL users are not in the database
  mysql_user: name="" host={{item}} state=absent check_implicit_admin=yes
  with_items:
    - localhost
    - "{{hostname}}"

- name: Delete MySQL test database
  mysql_db: name=test state=absent
