---
- name: Install packages needed to compile TFS
  apt: pkg={{ item }} state=latest
  with_items:
   - git
   - cmake
   - build-essential
   - liblua5.2-dev
   - libgmp3-dev
   - libmysqlclient-dev
   - libboost-system-dev

- name: Download latest TFS from git
  git: repo=https://github.com/otland/forgottenserver.git
       dest=/home/otsmanager/otserver

- name: Generate random MySQL root password
  command: openssl rand -base64 20
  register: randompass

- name: Create database user for TFS
  mysql_user: name=forgottenserver password="{{randompass.stdout}}" priv=forgottenserver.*:ALL state=present check_implicit_admin=yes

- name: Create database for TFS
  mysql_db: name=forgottenserver state=present

- name: Import MySQL database from schema.sql
  shell: (cat /home/otsmanager/otserver/schema.sql | mysql forgottenserver) && touch /home/otsmanager/.imported_db
          creates=/home/otsmanager/.imported_db

- name: Put password for database in config.lua
  lineinfile: dest=/home/otsmanager/otserver/config.lua regexp="^mysqlPass" line='mysqlPass = "{{randompass.stdout}}"'

- name: Chown for otsmanager
  command: chown otsmanager:otsmanager /home/otsmanager -R
