---
- name: Install packages needed to compile TFS
  apt: pkg={{ item }} state=latest
  with_items:
   - git
   - cmake
   - build-essential
   - libgmp3-dev
   - libmysqlclient-dev
   - libboost-system-dev
   - liblua5.2-dev

- name: Install LuaJIT package if available (since Ubuntu 14.04 Trusty) - TFS will automatically choose LuaJIT if installed
  apt: pkg=libluajit-5.1-dev state=latest
  ignore_errors: yes

- name: Download latest TFS from git
  git: repo=https://github.com/otland/forgottenserver.git
       dest=/home/otsmanager/forgottenserver

- name: Generate random MySQL password
  command: openssl rand -base64 18
  register: randompass

- name: Create database user for TFS
  mysql_user: name=forgottenserver password="{{randompass.stdout}}" priv=forgottenserver.*:ALL state=present check_implicit_admin=yes

- name: Create database for TFS
  mysql_db: name=forgottenserver state=present

- name: Import database for TFS
  mysql_db: name=forgottenserver state=import target=/home/otsmanager/forgottenserver/schema.sql

- name: Put password for database in config.lua
  lineinfile: dest=/home/otsmanager/forgottenserver/config.lua regexp="^mysqlPass" line='mysqlPass = "{{randompass.stdout}}"'

- name: Create build directory
  file: path=/home/otsmanager/forgottenserver/build owner=otsmanager group=otsmanager mode=0755 state=directory

- name: Cmake forgottenserver source
  command: cmake ..
           chdir=/home/otsmanager/forgottenserver/build
  tags: compile

- name: Compile forgottenserver source
  command: make
           chdir=/home/otsmanager/forgottenserver/build
  tags: compile           

- name: Chown for otsmanager
  command: chown otsmanager:otsmanager /home/otsmanager -R
